### ISSUE TITLE
How to obtain landmark_embedding.npy?

### ISSUE THREAD

**Issue by StarSapph1re** [initialneil/SplattingAvatar#10]
I attempted to run the train_splatting_avatar.py but it seems a landmark_embedding file is needed.
creating the FLAME Decoder
Traceback (most recent call last):
  File "/root/SplattingAvatar/train_splatting_avatar.py", line 43, in <module>
    frameset_train = make_frameset_data(config.dataset, split='train')
  File "/root/SplattingAvatar/dataset/dataset_helper.py", line 20, in make_frameset_data
    frameset = IMavatarDataset(dataset_config, split=split, frm_list=frm_list)
  File "/root/SplattingAvatar/dataset/imavatar_data.py", line 65, in __init__
    self.load_flame_json()
  File "/root/SplattingAvatar/dataset/imavatar_data.py", line 111, in load_flame_json
    self.flame = FLAME('model/imavatar/FLAME2020/generic_model.pkl', 
  File "/root/SplattingAvatar/model/imavatar/flame.py", line 51, in __init__
    lmk_embeddings = np.load(lmk_embedding_path, allow_pickle=True, encoding='latin1')
  File "/root/miniconda3/envs/splatting/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'model/imavatar/FLAME2020/landmark_embedding.npy'
There's no FLAME2020 in the original code and I created it, copying generic_model.pkl into it, but how to obtain landmark_embedding.npy?
Thanks so much for your greating work. Looking forward to your reply.

**Comment by Loppas** [comment]
I ran in the same issue. You can grab it here:

https://github.com/yfeng95/DECA/blob/master/data/landmark_embedding.npy

**Comment by StarSapph1re** [comment]
> I ran into the same issue. You can grab it here:
> 
> https://github.com/yfeng95/DECA/blob/master/data/landmark_embedding.npy

Thank you so much:)

**Comment by ApsaraJer** [comment]
Hello, my job here is the same as your operation, but my problem is that you have some differences and an error message is displayed：
Traceback (most recent call last):
  File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/train_splatting_avatar.py", line 43, in <module>
    frameset_train = make_frameset_data(config.dataset, split='train')
  File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/dataset/dataset_helper.py", line 20, in make_frameset_data
    frameset = IMavatarDataset(dataset_config, split=split, frm_list=frm_list)
  File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/dataset/imavatar_data.py", line 65, in __init__
    self.load_flame_json()
  File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/dataset/imavatar_data.py", line 73, in load_flame_json
    raise NotImplementedError
NotImplementedError
This error seems to indicate that 'the load_flame_json' method in the code has not been implemented yet. How should I proceed to address this? 
Excuse me for bothering you. Looking forward to your reply. Thank you
