### ISSUE TITLE
 Encountered an issue related to FLAME when running train_splatting_avatar.py. 

### ISSUE THREAD

**Issue by ApsaraJer** [initialneil/SplattingAvatar#30]
Hello, I attempted to run the train_splatting_avatar.py,but I encountered a problem that looks like FLAME is as follows as follows：
Traceback (most recent call last):
File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/train_splatting_avatar.py", line 43, in
frameset_train = make_frameset_data(config.dataset, split='train')
File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/dataset/dataset_helper.py", line 20, in make_frameset_data
frameset = IMavatarDataset(dataset_config, split=split, frm_list=frm_list)
File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/dataset/imavatar_data.py", line 65, in init
self.load_flame_json()
File "/mnt/SplattingAvatar/pytorch3d/SplattingAvatar/dataset/imavatar_data.py", line 73, in load_flame_json
raise NotImplementedError
NotImplementedError
There's no FLAME2020 in the original code and I created it, copying generic_model.pkl into it.
This error seems to indicate that 'the load_flame_json' method in the code has not been implemented yet. How should I proceed to address this?
Excuse me for bothering you. Looking forward to your reply. Thanks so much for your greating work.

**Comment by initialneil** [comment]
@ApsaraJer It means that `flame_params.json` is not existed in the data folder.

**Comment by wenxy68** [comment]
flame_params.jsonWhere can I obtain the flame_params.json file?

**Comment by guopengyuan** [comment]
sorry,I have same question
