### ISSUE TITLE
error of training Full-body Avatar

### ISSUE THREAD

**Issue by kato-taketo** [initialneil/SplattingAvatar#34]
Hi, thank you for your excellent work!

when I train Full-body Avatar, I got numpy error !
How to fix this error?
Please teach me!
[link](https://github.com/initialneil/SplattingAvatar#full-body-avatar)

```bash
(splatting) kato@KAMEX:~/デスクトップ/SplattingAvatar-kato$ python train_splatting_avatar.py --config "configs/splatting_avatar.yaml;configs/instant_avatar.yaml" --dat_dir ../Datasets/CVPR2024_SplattingAvatar-PeopleSnapshot/peoplesnapshot/female-3-casual
/home/kato/anaconda3/envs/splatting/lib/python3.9/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
/home/kato/anaconda3/envs/splatting/lib/python3.9/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
/home/kato/anaconda3/envs/splatting/lib/python3.9/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
Traceback (most recent call last):
  File "/home/kato/デスクトップ/SplattingAvatar-kato/train_splatting_avatar.py", line 45, in <module>
    frameset_train = make_frameset_data(config.dataset, split='train')
  File "/home/kato/デスクトップ/SplattingAvatar-kato/dataset/dataset_helper.py", line 23, in make_frameset_data
    frameset = InstantAvatarDataset(dataset_config, split=split, frm_list=frm_list)
  File "/home/kato/デスクトップ/SplattingAvatar-kato/dataset/instant_avatar_reader.py", line 39, in __init__
    self.load_pose_file()
  File "/home/kato/デスクトップ/SplattingAvatar-kato/dataset/instant_avatar_reader.py", line 104, in load_pose_file
    self.smpl_model = smplx_utils.create_smplx_model(**self.smpl_config)
  File "/home/kato/デスクトップ/SplattingAvatar-kato/model/smplx_utils/smplx_utils.py", line 41, in create_smplx_model
    smplx_model = smplx.create(model_path, gender=gender, model_type=model_type, ext=ext,
  File "/home/kato/デスクトップ/SplattingAvatar-kato/model/smplx_utils/smplx/body_models.py", line 2477, in create
    return SMPL(model_path, **kwargs)
  File "/home/kato/デスクトップ/SplattingAvatar-kato/model/smplx_utils/smplx/body_models.py", line 144, in __init__
    data_struct = Struct(**pickle.load(smpl_file,
  File "/home/kato/anaconda3/envs/splatting/lib/python3.9/site-packages/chumpy/__init__.py", line 11, in <module>
    from numpy import bool, int, float, complex, object, unicode, str, nan, inf
ImportError: cannot import name 'bool' from 'numpy' (/home/kato/anaconda3/envs/splatting/lib/python3.9/site-packages/numpy/__init__.py)
```

**Comment by kato-taketo** [comment]
In the __init__.py of chumpy, the errors were resolved by renaming and importing numpy's bool and other similar types as bool_ and so forth during installation.
